import { ComplaintInterface } from "../@types";

export const ComplaintDataList: ComplaintInterface[] = [
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'الحصر',
        ComplaintStatus: 'معلقة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,

        

    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'الإفتراضي',
        ComplaintStatus: 'محولة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'المكافحة',
        ComplaintStatus: 'مغلقة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635214,
        ComplaintDepartment: 'المكافحة',
        ComplaintStatus: 'مغلقة مع قسيمة',
                ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },

    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'الإفتراضي',
        ComplaintStatus: 'محولة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'الحصر',
        ComplaintStatus: 'معلقة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'الإفتراضي',
        ComplaintStatus: 'محولة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635214,
        ComplaintDepartment: 'المكافحة',
        ComplaintStatus: 'مغلقة مع قسيمة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    {
        id:Math.random(),
        ComplaintNumber: 35218635216,
        ComplaintDepartment: 'المكافحة',
        ComplaintStatus: 'مغلقة',
        ComplaintDate: '2023/5/3',
        ComplaintTimeFrame: '2023/5/3',
        TaxpayerName: 'لوريم ايبسوم',
        city:'cairo',
        area:'nasr city',
        taxpayerBranchName:'abbas',
        RIN:876-121-987,
        incentiveRegistered:true,
        taxPaterType:'VAT',
        compliantType:'receipt value is diff',
        customerName:'ahmed mohamed',
        customerMobileNumber:'0152668891' ,
        customerNID:6666666,
    },
    

]